
package practica1s12017_201503925;

import java.awt.FlowLayout;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.jdom2.Document;         
import org.jdom2.Element;          
import org.jdom2.JDOMException;    
import org.jdom2.input.SAXBuilder;
import java.util.List;
/**
 *
 * @author Sergio
 */
public class Inicio extends javax.swing.JFrame {

    
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDD");

        jButton1.setText("Cargar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Jugar");
        jButton2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton2ComponentShown(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JFileChooser seleccion= new JFileChooser();
    
        int seleccionado=seleccion.showOpenDialog(null);       
                if(seleccionado==JFileChooser.APPROVE_OPTION){
                    File archivo=seleccion.getSelectedFile();
                        cargarXML(archivo);
                    }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          this.dispose();
          Jugadores j= new Jugadores(sizeArreglo, diccionario, posx, posy, val);
          j.setLocationRelativeTo(null);
          j.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton2ComponentShown
        this.dispose();
        AgregarJugador jug= new AgregarJugador();
        jug.setVisible(true);
        
        jug.setLayout(new FlowLayout());
    }//GEN-LAST:event_jButton2ComponentShown

    
ListaSimple diccionario=new ListaSimple();
ListaSimple posx=new ListaSimple();
ListaSimple posy=new ListaSimple();
ListaSimple val=new ListaSimple();
int sizeArreglo;

    public void cargarXML(File archivo){
        try {
            SAXBuilder builder= new SAXBuilder();
            Document documento= (Document)builder.build(archivo);
       
            Element raiz= documento.getRootElement();
            
            List list = raiz.getChildren("diccionario");
            List list2= raiz.getChildren("dobles");
            List list3= raiz.getChildren("triples");
            
            sizeArreglo=Integer.parseInt(raiz.getChildText("dimension"));
            
            for (int i = 0; i < list2.size(); i++) {
                Element datos=(Element)list2.get(i);
                List aux= datos.getChildren("casilla");
                
                for (int j = 0; j < aux.size(); j++) {
                    Element d=(Element)aux.get(j);
                        posx.insertarFinal(d.getChildTextTrim("x"));
                        posy.insertarFinal(d.getChildTextTrim("y"));
                        val.insertarFinal(2);
                }
            }
            for (int i = 0; i < list3.size(); i++) {
                Element datos=(Element)list3.get(i);
                List aux= datos.getChildren("casilla");
                
                for (int j = 0; j < aux.size(); j++) {
                    Element d=(Element)aux.get(j);
                        posx.insertarFinal(d.getChildTextTrim("x"));
                        posy.insertarFinal(d.getChildTextTrim("y"));
                        val.insertarFinal(3);
                }
            }
            
            for (int i = 0; i < list.size(); i++) {
                Element datos =(Element)list.get(i);
                List listado = datos.getChildren("palabra");
                
                for (int j = 0; j < listado.size(); j++) {
                    Element componentes = (Element)listado.get(j);
                    diccionario.insertarFinal(componentes.getText());
                }
            }
            
            System.out.println("tam "+sizeArreglo);
            diccionario.imprimir();
            posx.imprimir();
            posy.imprimir();
            val.imprimir();
        } catch (JDOMException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
